# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: gamarra_connection
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
    ports:
      - "27028:27017"