export const limitReferents = 2

export const nationalitiesByCode = {
  AF : 'Afganistán',
  AL : 'Albania',
  DE : 'Alemania',
  AD : 'Andorra',
  AO : 'Angola',
  AI : 'Anguila',
  AQ : 'Antártida',
  AG : 'Antigua y Barbuda',
  SA : 'Arabia Saudita',
  DZ : 'Argelia',
  AR : 'Argentina',
  AM : 'Armenia',
  AW : 'Aruba',
  AU : 'Australia',
  AT : 'Austria',
  AZ : 'Azerbaiyán',
  BS : 'Bahamas',
  BD : 'Bangladés',
  BB : 'Barbados',
  BH : 'Baréin',
  BE : 'Bélgica',
  BZ : 'Belice',
  BJ : 'Benín',
  BM : 'Bermudas',
  BY : 'Bielorrusia',
  MM : 'Myanmar',
  BO : 'Bolivia',
  BA : 'Bosnia y Herzegovina',
  BW : 'Botsuana',
  BR : 'Brasil',
  BN : 'Brunéi Darussalam',
  BG : 'Bulgaria',
  BF : 'Burkina Faso',
  BI : 'Burundi',
  BT : 'Bután',
  CV : 'Cabo Verde',
  KH : 'Camboya',
  CM : 'Camerún',
  CA : 'Canadá',
  QA : 'Catar',
  BQ : 'Bonaire',
  TD : 'Chad',
  CL : 'Chile',
  CN : 'China',
  CY : 'Chipre',
  CO : 'Colombia',
  KM : 'Comoras',
  KR : 'Corea',
  CI : 'Costa de Marfil',
  CR : 'Costa Rica',
  HR : 'Croacia',
  CU : 'Cuba',
  CW : 'Curaçao',
  DK : 'Dinamarca',
  DM : 'Dominica',
  EC : 'Ecuador',
  EG : 'Egipto',
  SV : 'El Salvador',
  AE : 'Emiratos Árabes Unidos',
  ER : 'Eritrea',
  SK : 'Eslovaquia',
  SI : 'Eslovenia',
  ES : 'España',
  US : 'Estados Unidos',
  EE : 'Estonia',
  ET : 'Etiopía',
  PH : 'Filipinas',
  FI : 'Finlandia',
  FJ : 'Fiyi',
  FR : 'Francia',
  GA : 'Gabón',
  GM : 'Gambia',
  GE : 'Georgia',
  GH : 'Ghana',
  GI : 'Gibraltar',
  GD : 'Granada',
  GR : 'Grecia',
  GL : 'Groenlandia',
  GP : 'Guadalupe',
  GU : 'Guam',
  GT : 'Guatemala',
  GF : 'Guayana Francesa',
  GG : 'Guernsey',
  GN : 'Guinea',
  GW : 'Guinea-Bisáu',
  GQ : 'Guinea Ecuatorial',
  GY : 'Guyana',
  HT : 'Haití',
  HN : 'Honduras',
  HK : 'Hong Kong',
  HU : 'Hungría',
  IN : 'India',
  ID : 'Indonesia',
  IQ : 'Irak',
  IR : 'Irán',
  IE : 'Irlanda',
  BV : 'Isla Bouvet',
  IM : 'Isla de Man',
  CX : 'Isla de Navidad',
  NF : 'Isla Norfolk',
  IS : 'Islandia',
  KY : 'Islas Caimán',
  CC : 'Islas Cocos',
  CK : 'Islas Cook',
  FO : 'Islas Feroe',
  GS : 'Georgia del sur y las islas sandwich del sur',
  HM : 'Isla Heard e Islas McDonald',
  FK : 'Islas Malvinas',
  MP : 'Islas Marianas del Norte',
  MH : 'Islas Marshall',
  PN : 'Pitcairn',
  SB : 'Islas Salomón',
  TC : 'Islas Turcas y Caicos',
  UM : 'Islas de Ultramar Menores de Estados Unidos',
  VI : 'Islas Vírgenes',
  IL : 'Israel',
  IT : 'Italia',
  JM : 'Jamaica',
  JP : 'Japón',
  JE : 'Jersey',
  JO : 'Jordania',
  KZ : 'Kazajistán',
  KE : 'Kenia',
  KG : 'Kirguistán',
  KI : 'Kiribati',
  KW : 'Kuwait',
  LA : 'Lao',
  LS : 'Lesoto',
  LV : 'Letonia',
  LB : 'Líbano',
  LR : 'Liberia',
  LY : 'Libia',
  LI : 'Liechtenstein',
  LT : 'Lituania',
  LU : 'Luxemburgo',
  MO : 'Macao',
  MG : 'Madagascar',
  MY : 'Malasia',
  MW : 'Malaui',
  MV : 'Maldivas',
  ML : 'Malí',
  MT : 'Malta',
  MA : 'Marruecos',
  MQ : 'Martinica',
  MU : 'Mauricio',
  MR : 'Mauritania',
  YT : 'Mayotte',
  MX : 'México',
  FM : 'Micronesia',
  MD : 'Moldavia',
  MC : 'Mónaco',
  MN : 'Mongolia',
  ME : 'Montenegro',
  MS : 'Montserrat',
  MZ : 'Mozambique',
  NA : 'Namibia',
  NR : 'Nauru',
  NP : 'Nepal',
  NI : 'Nicaragua',
  NE : 'Níger',
  NG : 'Nigeria',
  NU : 'Niue',
  NO : 'Noruega',
  NC : 'Nueva Caledonia',
  NZ : 'Nueva Zelanda',
  OM : 'Omán',
  NL : 'Países Bajos',
  PK : 'Pakistán',
  PW : 'Palaos',
  PS : 'Palestina, Estado de',
  PA : 'Panamá',
  PG : 'Papúa Nueva Guinea',
  PY : 'Paraguay',
  PE : 'Perú',
  PF : 'Polinesia Francesa',
  PL : 'Polonia',
  PT : 'Portugal',
  PR : 'Puerto Rico',
  GB : 'Reino Unido',
  CF : 'República Centroafricana',
  CZ : 'República Checa',
  MK : 'Macedonia',
  CG : 'Congo',
  DO : 'República Dominicana',
  RE : 'Reunión',
  RW : 'Ruanda',
  RO : 'Rumania',
  RU : 'Rusia',
  EH : 'Sahara Occidental',
  WS : 'Samoa',
  AS : 'Samoa Americana',
  BL : 'San Bartolomé',
  KN : 'San Cristóbal y Nieves',
  SM : 'San Marino',
  MF : 'San Martín',
  PM : 'San Pedro y Miquelón',
  VC : 'San Vicente y las Granadinas',
  SH : 'Santa Helena',
  LC : 'Santa Lucía',
  ST : 'Santo Tomé y Príncipe',
  SN : 'Senegal',
  RS : 'Serbia',
  SC : 'Seychelles',
  SL : 'Sierra leona',
  SGP: 'Singapur',
  SX : 'Sint Maarten',
  SY : 'Siria',
  SO : 'Somalia',
  LK : 'Sri Lanka',
  SZ : 'Suazilandia',
  ZA : 'Sudáfrica',
  SD : 'Sudán',
  SS : 'Sudán del Sur',
  SE : 'Suecia',
  CH : 'Suiza',
  SR : 'Surinam',
  SJ : 'Svalbard y Jan Mayen',
  TH : 'Tailandia',
  TW : 'Taiwán',
  TZ : 'Tanzania',
  TJ : 'Tayikistán',
  IO : 'Territorio Británico del Océano Índico',
  TF : 'Territorios Australes Franceses',
  TL : 'Timor-Leste',
  TG : 'Togo',
  TK : 'Tokelau',
  TO : 'Tonga',
  TT : 'Trinidad y Tobago',
  TN : 'Túnez',
  TM : 'Turkmenistán',
  TR : 'Turquía',
  TV : 'Tuvalu',
  UA : 'Ucrania',
  UG : 'Uganda',
  UY : 'Uruguay',
  UZ : 'Uzbekistán',
  VU : 'Vanuatu',
  VE : 'Venezuela',
  VN : 'Vietnam',
  WF : 'Wallis y Futuna',
  YE : 'Yemen',
  DJ : 'Yibuti',
  ZM : 'Zambia',
  ZW : 'Zimbabue'
}

